### PR TITLE
Add allscoped

### LINKED ISSUE #10: Allow to have all the styles scoped
What do you think about this feature?

Allow a parameter in options to have all the style files as scoped without need to use the .scoped extension.

### PR DESCRIPTION
**Pull request by CKGrafico**
Fix #10

### CODE REVIEW

**Comment by CKGrafico** [comment]
I've edited and old version from my local xD 5 min

**Comment by pksunkara** [comment]
I can't accept the PR as it is now. 😞

**Comment by CKGrafico** [comment]
My fault, check now

**Comment by CKGrafico** [comment]
Better to start again

**Comment by pksunkara** [comment]
Code looks good. Codeclimate auto comments issues though.

**Pull request closed without merging**
